a = int(input())
r = input()
arr = r.split()
b = int(arr[0])
c = int(arr[1])
d = int(arr[2])
e = int(arr[3])

print(1 if a > b else 0)
print(1 if a > c else 0)
print(1 if a > d else 0)
print(1 if a > e else 0)